const chatMessages = [
  "Hi everyone, how's it going?",
  "Hello! Excited to be here!",
  "Good morning! What's new today?",
  "Can someone help me with this question?",
  "Wow, that's a great point!",
  "I completely agree with you.",
  "Does anyone have a solution for this?",
  "Thanks for sharing!",
  "Can we discuss this further?",
  "I never thought of it that way!",
  "What's the agenda for today?",
  "How do you feel about this topic?",
  "Can we circle back to that point?",
  "That was very insightful, thank you!",
  "Can you clarify what you meant?",
  "Anyone else has thoughts on this?",
  "This is such a valuable discussion.",
  "Sorry, I didn't quite catch that.",
  "Could you repeat the last part?",
  "This is exactly what I needed!",
  "Wow, that's an interesting perspective.",
  "Thanks, that really helps!",
  "I appreciate your input on this.",
  "Does anyone have any examples?",
  "How can I learn more about this?",
  "Where can I find additional resources?",
  "Thanks for explaining that!",
  "That's a great suggestion!",
  "What are the next steps for this?",
  "I have a quick question.",
  "Can someone share their experience?",
  "I feel the same way!",
  "Great point, I hadn't considered that.",
  "Is this the final decision?",
  "Who else agrees with this?",
  "How does this compare to other options?",
  "What are the benefits of this approach?",
  "Can you elaborate on that?",
  "This is a really helpful discussion.",
  "I just joined; what did I miss?",
  "What are the challenges here?",
  "Is there a workaround for this?",
  "Thanks, this is very helpful!",
  "How long will this take to implement?",
  "What are the key takeaways?",
  "Where do we go from here?",
  "What's the timeline for this?",
  "What are the risks involved?",
  "Can someone summarize the main points?",
  "I have a different perspective on this.",
  "Has anyone tried this approach?",
  "What tools are you using for this?",
  "What are the alternatives?",
  "I like the way you explained that!",
  "This is such a productive discussion.",
  "Who can I contact for more details?",
  "What inspired this idea?",
  "Can you share more about this?",
  "What are the common pitfalls?",
  "How can I contribute to this?",
  "I'm learning so much from this!",
  "This is exactly what I needed!",
  "Where do you see the challenges?",
  "Does this align with our goals?",
  "What are the key success factors?",
  "Can we test this hypothesis?",
  "What are the dependencies here?",
  "Thanks for bringing this up!",
  "How will this impact other teams?",
  "Can we get more data on this?",
  "What does success look like?",
  "What are the limitations of this?",
  "How does this fit into the big picture?",
  "Thanks for sharing your experience!",
  "I appreciate your transparency.",
  "This resonates with me deeply.",
  "How do we prioritize this?",
  "What would you recommend instead?",
  "What other options are available?",
  "Is this scalable?",
  "How did you arrive at this conclusion?",
  "What is the impact of this decision?",
  "How can we align on this?",
  "I'm excited to see where this goes!",
  "This is such a great learning opportunity.",
  "How can I apply this in my work?",
  "What would you do in this situation?",
  "How can we make this even better?",
  "What are the trade-offs here?",
  "Can you point me to some examples?",
  "How do you measure success for this?",
  "What's the rationale behind this?",
  "Does anyone have a counterpoint?",
  "What are your main takeaways?",
  "I completely understand now, thanks!",
  "Can we brainstorm ideas for this?",
  "What's the process for implementing this?",
  "Who are the stakeholders involved?",
  "This is such an inspiring discussion!",
  "How can we keep this momentum going?",
];

export const RandomMessageGenerator = () => {
  let randomNum = Math.round(Math.random() * chatMessages.length);
  return chatMessages[randomNum];
};
